// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import "fyne.io/fyne/v2"

var ffmpegwin = &fyne.StaticResource{
	StaticName: "ffmpeg.exe",
	StaticContent: []byte(""),
		}
var ffmpegmac = &fyne.StaticResource{
	StaticName: "ffmpeg",
	StaticContent: []byte(""),
}
		